### ISSUE TITLE
Let the troubleshooting begin

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/us_ensembles#10]
OK, now that we have all the state seeds in, I'm hitting a few issues. 

**CA**

CA is giving me:

```
Traceback (most recent call last):
  File "20_run_simulation.py", line 163, in <module>
    total_steps=100000
  File "/hpc/home/nce8/miniconda3/lib/python3.7/site-packages/gerrychain/chain.py", line 47, in __init__
    raise ValueError(message)
ValueError: The given initial_state is not valid according is_valid. The failed constraints were: Bounds(population,(630236.8517087759, 655960.8048397463))
```

You mentioned in #8 these were 2% thresholds -- were they 5% by any chance?

**FL**: 

Same issue, but here I know it should be 5%, right?

```
Traceback (most recent call last):
  File "20_run_simulation.py", line 163, in <module>
    total_steps=100000
  File "/hpc/home/nce8/miniconda3/lib/python3.7/site-packages/gerrychain/chain.py", line 47, in __init__
    raise ValueError(message)
ValueError: The given initial_state is not valid according is_valid. The failed constraints were: Bounds(population,(681269.4143027109, 709076.3291722094))
```

 **WY**: 

Wyoming is giving me: 

```
Traceback (most recent call last):
  File "20_run_simulation.py", line 181, in <module>
    for part in chain:
  File "/hpc/home/nce8/miniconda3/lib/python3.7/site-packages/gerrychain/chain.py", line 67, in __next__
    proposed_next_state = self.proposal(self.state)
  File "/hpc/home/nce8/miniconda3/lib/python3.7/site-packages/gerrychain/proposals/tree_proposals.py", line 35, in recom
    edge = random.choice(tuple(partition["cut_edges"]))
  File "/hpc/home/nce8/miniconda3/lib/python3.7/random.py", line 261, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
```

Which I presume is because... it only has one district! In fact, does this mean I should be ignoring any 1 district states as useless?

**Comment by nickeubank** [comment]
Fixed all the single-district states. 


But bumping threshold to 5% still causing problems with FL and CA:

```
3.1                                            File: slurm_reports_13463439_24.output                                                                                                

Traceback (most recent call last):
  File "20_run_simulation.py", line 168, in <module>
    total_steps=100000
  File "/hpc/home/nce8/miniconda3/lib/python3.7/site-packages/gerrychain/chain.py", line 47, in __init__
    raise ValueError(message)
ValueError: The given initial_state is not valid according is_valid. The failed constraints were: Bounds(population,(660414.228150587, 729931.5153243331))
```

Thoughts?

**Comment by nickeubank** [comment]
Also failing at 0.052 (so not a floating point error at threshold).
